spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/microservice
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:55}

eureka.instance.prefer-ip-address=true
eureka.client.service-url.default-zone=https://eureka-server-565634063005.us-central1.run.app/

application-description=Stand Microservice
application-license=API Licence
application-version=1.0