# Service identification
spring.application.name=config-server
server.port=8888
spring.profiles.active=local
# Git repo for configurations
spring.cloud.config.server.git.uri=https://github.com/SumoTechGeeks/stand-microservice
spring.cloud.config.server.git.search-paths=config
# Expose actuator endpoints (required for Eureka health check)
management.endpoints.web.exposure.include=*
# Eureka client configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=https://eureka-service-565634063005.us-central1.run.app/eureka/
# Optional but recommended
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30